[package]
name = "probe-rs-cli-util"
version = "0.11.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch", "Dominik Boehi <dominik.boehi@gmail.com>"]
edition = "2018"
description = "Helper library for CLI applications based on probe-rs."
documentation = "https://docs.rs/probe-rs-cli-util/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[features]
default = ["anyhow"]

[dependencies]
thiserror = "1.0"
anyhow = { version = "1.0", optional = true }
indicatif = "0.16.0"
env_logger = "0.9.0"
log = "0.4.0"
once_cell = "1.7.2"
colored = "2.0.0"
probe-rs = { version = "0.11.0", path = "../probe-rs" }
cargo_toml = "0.9.0"
serde = { version = "1.0.115", features = [ "derive" ] }
cargo_metadata = "0.14.0"
dunce = "1.0.1"
sentry = { version = "0.22.0", features = ["anyhow"], optional = true }
simplelog = "0.10.0"
terminal_size = "0.1.13"
structopt = "0.3"