[package]
name = "probe-rs-cli-util"
version = "0.9.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch", "Dominik Boehi <dominik.boehi@gmail.com>"]
edition = "2018"
description = "Helper library for CLI applications based on probe-rs."
documentation = "https://docs.rs/probe-rs-cli-util/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.16"
anyhow = "1.0"
log = "0.4.0"
probe-rs = { version = "0.9.0", path = "../probe-rs" }
cargo_toml = "0.8.1"
serde = { version = "1.0.115", features = [ "derive" ] }
cargo_metadata = "0.12.0"
