[package]
name = "probe-rs-cli-util"
version = "0.13.0"
authors = [
    "Noah HÃ¼sser <yatekii@yatekii.ch>",
    "Dominik Boehi <dominik.boehi@gmail.com>",
]
edition = "2021"
description = "Helper library for CLI applications based on probe-rs."
documentation = "https://docs.rs/probe-rs-cli-util/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[features]
default = ["anyhow"]

[dependencies]
probe-rs-rtt = { path = "../rtt" }
probe-rs = { version = "0.13.0", path = "../probe-rs" }

thiserror = "1.0"
anyhow = { version = "1.0", optional = true }
indicatif = "0.16.0"
env_logger = "0.9.0"
log = "0.4.0"
once_cell = "1.7.2"
colored = "2.0.0"
cargo_toml = "0.11.1"
serde = { version = "1.0.115", features = ["derive"] }
cargo_metadata = "0.15.0"
dunce = "1.0.1"
sentry = { version = "0.27.0", features = ["anyhow"], optional = true }
simplelog = "0.12.0"
terminal_size = "0.2.0"
clap = { version = "3.0", features = ["derive"] }
byte-unit = "4.0.13"
chrono = { version = "0.4", features = ["serde"] }
goblin = "0.5.1"
num-traits = "0.2.14"
defmt-decoder = { version = "0.3.1", features = ["unstable"] }
