required_approvals = 1
block_labels = ["wip"]
delete_merged_branches = true
status = [
    "Check (ubuntu-latest)",
    "Check (windows-latest)",
    "Check (macos-latest)",
    "Test Suite (ubuntu-latest)",
    "Test Suite (windows-latest)",
    "Rustfmt",
]
# pr_status = ["Changelog"]
