[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2018"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.2.4"

[dependencies]
addr2line = "0.15"
ansi_term = "0.12"
anyhow = "1.0"
colored = "2.0"
defmt-decoder = { version = "=0.2.2", features = ['unstable'] }
difference = "2.0"
either = "1.6"
gimli = "0.24"
git-version = "0.3"
hidapi = "1.2"
log = "0.4"
object = "0.24"
probe-rs = "0.11"
probe-rs-rtt = "0.11"
rustc-demangle = "0.1"
signal-hook = "0.3"
structopt = "0.3"

[dev-dependencies]
insta = "1.7"
os_pipe = "0.9"
pretty_assertions = "0.7"
rstest = "0.10"
