[workspace.package]
version = "0.21.0"
edition = "2021"

documentation = "https://docs.rs/probe-rs/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"


[workspace]
resolver = "2"
members = [
    "probe-rs",
    "probe-rs-target",
    "rtthost",
    "smoke-tester",
    "xtask",
    "target-gen",
]

[workspace.dependencies]
probe-rs = { path = "probe-rs", version = "0.21.0" }
probe-rs-target = { path = "probe-rs-target", version = "0.21.0" }

log = "0.4.20"
pretty_env_logger = "0.5.0"
thiserror = "1.0"
anyhow = "1.0.75"

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.3.1"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.73.0"
# CI backends to support
ci = ["github"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
# Build only the required packages, and individually
precise-builds = true
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.xz"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Publish jobs to run in CI
pr-run-mode = "plan"

# Needed because the file is edited to add Linux build deps
allow-dirty = ["ci"]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
