[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2021"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.3.6"

[dependencies]
addr2line = { version = "0.19", default-features = false, features = [
    "fallible-iterator",
    "std-object",
    "rustc-demangle",
    "cpp_demangle",
] }
anyhow = "1"
clap = { version = "4.0", features = ["derive", "env"] }
colored = "2"
defmt-decoder = { version = "=0.3.4", features = ["unstable"] }
gimli = { version = "0.27", default-features = false }
git-version = "0.3"
log = "0.4"
object = { version = "0.30", default-features = false }
probe-rs = "0.17"
signal-hook = "0.3"

[dev-dependencies]
dirs = "4"
# insta 1.12 introduces breaking changes to the snapshot tests. it's fixable, but takes time.
insta = "~1.11"
os_pipe = "1.0"
pretty_assertions = "1"
rstest = { version = "0.16", default-features = false }
nix = "0.26"
serial_test = { version = "1", default-features = false }

[features]
ftdi = ["probe-rs/ftdi"]
