[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2018"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.2.0"

[dependencies]
addr2line = "0.14.1"
ansi_term = "0.12.1"
anyhow = "1.0.32"
arrayref = "0.3.6"
colored = "2.0.0"
defmt-decoder = { git = "https://github.com/knurling-rs/defmt", tag = "defmt-decoder-v0.2.0", version = "=0.2.0", features = ['unstable'] }
difference = "2.0.0"
gimli = "0.23.0"
log = "0.4.11"
# an addr2line trait is implement for a type in this particular version
object = "0.22.0"
probe-rs = "0.10.0"
probe-rs-rtt = "0.10.0"
rustc-demangle = "0.1.16"
signal-hook = "0.3.4"
structopt = "0.3.15"
hidapi = "1.2.5"
