[package]
name = "probe-run"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
arrayref = "0.3.6"
ctrlc = "3.1.6"
decoder = { git = "https://github.com/knurling-rs/defmt", branch = "main", optional = true }
elf2table = { git = "https://github.com/knurling-rs/defmt", branch = "main", optional = true }
env_logger = "0.7.1"
gimli = "0.22.0"
log = "0.4.11"
probe-rs = "0.6.0"
probe-rs-rtt = "0.1.0"
rustc-demangle = "0.1.16"
structopt = "0.3.15"
xmas-elf = "0.7.0"

[features]
defmt = ["elf2table", "decoder"]