[package]
name = "memory"
version = "0.1.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
log = "0.4.6"
num = "0.2"
num-traits = "*"
enum-primitive-derive = "*"
coresight = { path = "../coresight" }
jep106 = "0.2.2"
ihex = "1.1.2"
scroll = "*"