[package]
name = "xtask"
version.workspace = true
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2021"
publish = false

[dependencies]
xshell = "0.2"
regex = "1.7"
clap = { version = "4", features = ["derive"] }
