[package]
name = "xtask"
version.workspace = true
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2021"
publish = false

[dependencies]
xshell = "0.2"
regex = "1.10"
clap = { version = "4", features = ["derive"] }
chrono = "0.4.31"
anyhow.workspace = true
serde_json = "1.0.108"
serde = { version = "1.0.190", features = ["derive"] }
