[package]
name = "cargo-flash"
version = "0.5.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.com>"]
edition = "2018"
description = "A utility to flash ARM cores with ELFs directly from within cargo."
documentation = "https://docs.rs/cargo-flash/"
homepage = "https://github.com/probe-rs/cargo-flash"
repository = "https://github.com/probe-rs/cargo-flash"
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.3.2"
cargo-project = "0.2.3"
failure = "0.1.5"
indicatif = "0.14.0"
env_logger = "0.7.1"
log = "0.4.0"
lazy_static = "1.4.0"
colored = "1.8.3"
probe-rs = { version = "0.5.0" }
gdb-server = { version = "0.5.0" }
