[package]
name = "cli"
version = "0.2.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"

[dependencies]
ocd = { path = "../ocd", version = "0.2.0" }
ocd-targets = { path = "../ocd-targets", version = "0.2.0" }

pretty_env_logger = "0.3.0"
log = "0.4.6"
structopt = "0.2.14"
scroll = "0.9.2"
rustyline = "5.0.2"
capstone = "0.6.0"
ron = "0.5.1"
memmap = "0.7.0"
ihex = "1.1.2"
colored = "1.8.0"
