[package]
name = "cargo-embed"
version = "0.8.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2018"
description = "A utility to develop software for embedded ARM and RISC-V cores."
documentation = "https://docs.rs/cargo-embed/"
homepage = "https://github.com/probe-rs/cargo-embed"
repository = "https://github.com/probe-rs/cargo-embed"
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[dependencies]
structopt = "0.3.2"
cargo-project = "0.2.3"
indicatif = "0.15.0"
env_logger = "0.7.1"
log = { version = "0.4.0", features = ["serde"] }
lazy_static = "1.4.0"
colored = "1.8.3"
probe-rs = { version = "0.8.0" }
gdb-server = { version = "0.8.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.51" }
config = { version = "0.9.0", features = ["toml", "json", "yaml"], default-features = false }
probe-rs-rtt = { version = "0.3.0" }
chrono = "0.4"
crossterm = "0.17.0"
derivative = "2.1.0"
goblin = "0.2.0"
tui = { version = "0.9.0", default-features = false, features = ["crossterm"] }
anyhow = "1.0.31"
textwrap = "0.11.0"

[patch.crates-io]
probe-rs = { git = "https://github.com/probe-rs/probe-rs" }
