[package]
name = "cargo-embed"
version = "0.10.1"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2018"
description = "A utility to develop software for embedded ARM and RISC-V cores."
documentation = "https://docs.rs/cargo-embed/"
homepage = "https://github.com/probe-rs/cargo-embed"
repository = "https://github.com/probe-rs/cargo-embed"
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[features]
default = []
ftdi = ["probe-rs/ftdi"]
sentry = ["probe-rs-cli-util/sentry"]

[dependencies]
probe-rs = { version = "0.10.0", git = "https://github.com/probe-rs/probe-rs" }
gdb-server = { version = "0.10.0", git = "https://github.com/probe-rs/probe-rs"  }
probe-rs-cli-util = { version = "0.10.0", git = "https://github.com/probe-rs/probe-rs", default-features = false }

structopt = "0.3.18"
git-version = "0.3.4"
indicatif = "0.15.0"
env_logger = "0.8.2"
log = { version = "0.4.13", features = ["serde"] }
lazy_static = "1.4.0"
colored = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.62" }
config = { version = "0.10.1", features = ["toml", "json", "yaml"], default-features = false }
probe-rs-rtt = { version = "0.10.0", git = "https://github.com/probe-rs/probe-rs-rtt" }
chrono = "0.4"
# Version 0.17.8 doesn't compile on Windows
crossterm = "<= 0.17.7"
goblin = "0.3.1"
tui = { version = "0.13.0", default-features = false, features = ["crossterm"] }
anyhow = "1.0.38"
textwrap = "0.13.2"
defmt-decoder = { version = "0.1.3" }
defmt-elf2table = { version = "0.1.0", features = ['unstable'] }
