[package]
name = "target-gen"
version.workspace = true
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition.workspace = true
description = "A cli tool to create new target files for probe-rs ot of CMSIS-Packs."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs", version = "0.17.0", default-features = false }
probe-rs-target = { path = "../probe-rs-target", version = "0.17.0", default-features = false }
cmsis-pack = { version = "0.6.2" }
goblin = { version = "0.6.1", default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
    "archive",
    "std",
] }
scroll = "0.11.0"
serde_yaml = "^0.9"
log = "0.4.17"
zip = "0.6.4"
clap = { version = "4.1", features = ["derive"] }
colored = "2"
base64 = "0.21.0"
anyhow = "1.0.69"
reqwest = { version = "0.11.14", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.16", features = [
    "env-filter",
    "tracing-log",
] }
xshell = { version = "0.2", default-features = false }
cargo_metadata = { version = "0.15", default-features = false }
indicatif = { version = "0.17", default-features = false }

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
assert_fs = "1.0.10"
