[package]
name = "target-gen"
version.workspace = true
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition.workspace = true
description = "A cli tool to create new target files for probe-rs ot of CMSIS-Packs."
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs", version = "0.24.0" }
probe-rs-target = { path = "../probe-rs-target", version = "0.24.0", default-features = false }
cmsis-pack = "0.7.0"
jep106 = "0.2.8"
goblin = { version = "0.9.0", default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
    "archive",
    "std",
] }
scroll = "0.12.0"
serde_yaml = "0.9"
log = "0.4.21"
zip = { version = "2.0.0", default-features = false, features = [
    "deflate64",
    "deflate",
    "lzma",
    "time",
    "zstd",
] }
clap = { version = "4.5", features = ["derive"] }
colored = "2"
anyhow.workspace = true
reqwest = { version = "0.12.4", features = [
    "json",
    "rustls-tls",
], default-features = false }
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "tracing-log",
] }
xshell = { version = "0.2", default-features = false }
parse_int = "0.6"

[dev-dependencies]
tempfile = "3.0"
insta = { version = "1.38", default-features = false, features = ["yaml"] }

[lints]
workspace = true
