[package]
name = "target-gen"
version = "0.5.0"
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { git = "https://github.com/probe-rs/probe-rs.git", default-features = false }
cmsis-pack = { git = "https://github.com/probe-rs/cmsis-pack-manager.git" }

goblin = "0.2.0"
scroll = "0.10.1"
num-traits = "0.2.10"
num-derive = "0.3.0"
serde_yaml = "0.8.11"
log = "0.4.8"
zip = "0.5.3"
structopt = "0.3.2"
base64 = "0.12.3"
simplelog = "0.8.0"
anyhow = "1.0.28"
reqwest = { version = "0.10.4", features = ["json", "blocking"] }
serde = { version = "1.0.106", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["rt-core", "macros", "rt-threaded", "blocking"] }

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1"
assert_fs = "1.0.0"
