[package]
name = "target-gen"
version = "0.12.0"
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition = "2018"
description = "A cli tool to create new target files for probe-rs ot of CMSIS-Packs."
documentation = "https://docs.rs/probe-rs/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs", version = "0.12.0", default-features = false }
probe-rs-target = { path = "../probe-rs-target", version = "0.12.0", default-features = false }
cmsis-pack = { version = "0.5.0" }

# , path = "../cmsis-pack-manager/rust/cmsis-pack"
# , git = "https://github.com/probe-rs/cmsis-pack-manager.git"

goblin = "0.4.3"
scroll = "0.10.1"
serde_yaml = "0.8.23"
log = "0.4.8"
zip = "0.5.9"
structopt = "0.3.2"
base64 = "0.13.0"
simplelog = "0.11.1"
anyhow = "1.0.51"
reqwest = { version = "0.11.7", features = ["json", "blocking"] }
serde = { version = "1.0.131", features = ["derive"] }
# chrono = { version = "0.4.0", features = ["serde"] }
futures = "0.3.19"
tokio = { version = "1.14.0", features = ["macros", "rt", "rt-multi-thread"] }

[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "2.1.0"
assert_fs = "1.0.0"
