[package]
name = "gdb-server"
version = "0.1.0"
authors = ["Noah HÃ¼sser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs", version = "0.2.0" }
gdb-protocol = { version = "0.1.0" }
recap = "0.1.1"
serde = "1.0.1"
pretty_env_logger = "0.3.0"
structopt = "*"